"""PDF export tests - a stand-in plays the browser, except in the last test,
which prints a real report with Edge/Chrome when one is installed.

Run directly:

    python tests/test_pdfexport.py

or with pytest:

    pytest -q tests
"""

from __future__ import annotations

import collections
import contextlib
import os
import re
import sys
import tempfile
import time
from pathlib import Path

# Make the package importable when run as a plain script.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import pandas as pd  # noqa: E402
from pypdf import PdfReader, PdfWriter  # noqa: E402

from github_contrib import htmlreport, pdfexport  # noqa: E402
from github_contrib.webapp import pdf_env  # noqa: E402

MB = 1024 * 1024


@contextlib.contextmanager
def patched(target, **values):
    """Temporarily replace attributes of ``target`` (a module or object)."""
    saved = {name: getattr(target, name) for name in values}
    for name, value in values.items():
        setattr(target, name, value)
    try:
        yield
    finally:
        for name, value in saved.items():
            setattr(target, name, value)


@contextlib.contextmanager
def env_vars(**values):
    """Temporarily set (or, with None, remove) environment variables."""
    saved = {name: os.environ.get(name) for name in values}
    for name, value in values.items():
        if value is None:
            os.environ.pop(name, None)
        else:
            os.environ[name] = value
    try:
        yield
    finally:
        for name, value in saved.items():
            if value is None:
                os.environ.pop(name, None)
            else:
                os.environ[name] = value


def _commits(months: dict[str, int]) -> pd.DataFrame:
    """``count`` commits in each month ("2026-01": 3, ...)."""
    rows = []
    for month, count in months.items():
        for day in range(count):
            n = len(rows)
            rows.append({
                "authored_date": f"{month}-{day % 28 + 1:02d}T10:{n % 60:02d}:00Z",
                "sha": f"c{n:06x}" + "0" * 33,
                "url": f"https://github.com/o/r/commit/{n:040x}",
                "additions": 3,
                "deletions": 1,
                "full_name": "o/r",
                "branch": "main",
                # Escaped by the report, so it can't pass for a table row.
                "message_first_line": f"Change {n} <tr> & more" if n == 1 else f"Change {n}",
            })
    return pd.DataFrame(rows)


def _report_html(months: dict[str, int]) -> str:
    """A report page with only the appendix, built from the report's own
    markup, stylesheet and script."""
    return (
        "<!doctype html><html lang='en'><head><meta charset='utf-8'>"
        f"<meta http-equiv='Content-Security-Policy' content=\"{htmlreport.REPORT_CSP}\">"
        f"<style>{htmlreport._CSS}</style></head><body><div class='wrap'>"
        "<section><h2>At a glance</h2></section>"
        f"{htmlreport._render_commit_timeline(_commits(months))}"
        "<footer>Generated by github-contrib</footer></div>"
        f"<script>{htmlreport._SCRIPT}</script></body></html>"
    )


def _fake_browser(calls: list[str]):
    """Stands in for ``_run_browser``: writes a one-page PDF per print."""

    def run(cmd: list[str], _log_path: Path, _deadline: float) -> tuple[str, int]:
        target = Path(next(a for a in cmd if a.startswith("--print-to-pdf=")).split("=", 1)[1])
        calls.append(cmd[-1].rsplit("#", 1)[1])
        writer = PdfWriter()
        writer.add_blank_page(width=612, height=792)
        writer.add_metadata({"/Title": "GitHub Contribution Report"})
        with open(target, "wb") as fh:
            writer.write(fh)
        return "done", 0

    return run


def test_appendix_rows_follow_the_report_markup():
    rows = pdfexport.appendix_rows(_report_html({"2026-01": 3, "2026-02": 2}))
    assert rows == [True, False, False, False, True, False, False], rows
    # No marker (no appendix, or a report made before parts existed): one go.
    assert pdfexport.appendix_rows("<section id='commit-timeline'><tbody><tr></tr></tbody></section>") == []
    assert pdfexport.appendix_rows("<html></html>") == []
    print("ok  test_appendix_rows_follow_the_report_markup")


def test_plan_parts_covers_every_row_once_and_cuts_at_months():
    def check(rows: list[bool], size: int) -> list[tuple[int, int]]:
        parts = pdfexport.plan_parts(rows, size)
        assert parts[0][0] == 0 and parts[-1][1] == len(rows), parts
        assert all(start < end for start, end in parts), parts
        assert all(parts[i][1] == parts[i + 1][0] for i in range(len(parts) - 1)), parts
        assert all(end - start <= size for start, end in parts[:-1]), parts
        assert parts[-1][1] - parts[-1][0] <= size + size // 4, parts
        return parts

    three_months = ([True] + [False] * 150) * 3
    # Each part ends where a month begins.
    assert check(three_months, 200) == [(0, 151), (151, 302), (302, 453)]
    # One long month is cut at the size limit.
    assert check([True] + [False] * 500, 200) == [(0, 200), (200, 400), (400, 501)]
    # A short tail joins the last part rather than making its own.
    assert check([True] + [False] * 209, 200) == [(0, 210)]
    for size in (1, 2, 3, 7):
        check(three_months, size)
    assert pdfexport.plan_parts([], 200) == []
    print("ok  test_plan_parts_covers_every_row_once_and_cuts_at_months")


def test_long_appendix_prints_in_parts_and_joins_them():
    calls: list[str] = []
    with tempfile.TemporaryDirectory() as tmp:
        html = Path(tmp) / "report.html"
        html.write_text(_report_html({"2026-01": 150, "2026-02": 150, "2026-03": 150}), encoding="utf-8")
        with patched(pdfexport, find_browser=lambda: "chromium", _run_browser=_fake_browser(calls)):
            with env_vars(PDF_PART_ROWS="200"):
                assert pdfexport.export_pdf(html) == html.with_suffix(".pdf")
            assert calls == ["print=0-151", "print=151-302", "print=302-453"], calls
            reader = PdfReader(html.with_suffix(".pdf"))
            assert len(reader.pages) == 3 and reader.metadata.title == "GitHub Contribution Report"
            assert sorted(p.name for p in Path(tmp).iterdir()) == ["report.html", "report.pdf"]

            # Short enough (or parts turned off): printed in one go, as before.
            for rows in ("1000", "0"):
                calls.clear()
                with env_vars(PDF_PART_ROWS=rows):
                    assert pdfexport.export_pdf(html) == html.with_suffix(".pdf")
                assert calls == ["print"], calls
    print("ok  test_long_appendix_prints_in_parts_and_joins_them")


def test_browser_is_stopped_before_the_server_runs_out_of_memory():
    with tempfile.TemporaryDirectory() as tmp:
        marker = Path(tmp) / "still-running"
        # Writes the marker unless it is stopped first.
        sleeper = [sys.executable, "-c",
                   "import sys, time, pathlib; time.sleep(1.5); pathlib.Path(sys.argv[1]).write_text('x')",
                   str(marker)]
        log_path = Path(tmp) / "browser.log"
        started = time.monotonic()
        with patched(pdfexport, memory_use=lambda: (460 * MB, 512 * MB)):
            assert pdfexport._run_browser(sleeper, log_path, time.monotonic() + 60) == ("memory", None)
        with patched(pdfexport, memory_use=lambda: (100 * MB, 512 * MB)):
            assert pdfexport._run_browser(sleeper, log_path, time.monotonic() + 0.3) == ("timeout", None)
            assert time.monotonic() - started < 5, "stopped at once"
            time.sleep(2.5)
            assert not marker.exists(), "the stopped process (and its children) must be gone"
            # Enough memory: a print that finishes is left alone.
            assert pdfexport._run_browser([sys.executable, "-c", "pass"], log_path, time.monotonic() + 60) == ("done", 0)
        # No memory figures (not Linux): only the time limit applies.
        with patched(pdfexport, memory_use=lambda: None):
            assert pdfexport._run_browser([sys.executable, "-c", "pass"], log_path, time.monotonic() + 60) == ("done", 0)
    print("ok  test_browser_is_stopped_before_the_server_runs_out_of_memory")


def test_exit_status_says_when_memory_ran_out():
    with tempfile.TemporaryDirectory() as tmp:
        html = Path(tmp) / "report.html"
        html.write_text("<html></html>", encoding="utf-8")
        for outcome, status in (("memory", pdfexport.EXIT_NO_MEMORY), ("timeout", 1)):
            with patched(pdfexport, find_browser=lambda: "chromium", _run_browser=lambda *_a, o=outcome: (o, None)):
                assert pdfexport.main([str(html)]) == status
        assert not html.with_suffix(".pdf").exists()
    print("ok  test_exit_status_says_when_memory_ran_out")


def test_memory_use_reads_the_container_limit():
    files = {
        "/sys/fs/cgroup/memory.current": "400000000\n",
        "/sys/fs/cgroup/memory.max": "536870912\n",
        "/sys/fs/cgroup/memory.stat": "anon 300000000\ninactive_file 50000000\nactive_file 1000\n",
        "/proc/meminfo": "MemTotal:        8000000 kB\nMemAvailable:    6000000 kB\n",
    }
    with patched(pdfexport, _read=lambda path: files.get(path, "")), env_vars(PDF_MEMORY_LIMIT_MB=None):
        # cgroup v2; inactive file cache doesn't count (the kernel drops it first).
        assert pdfexport.memory_use() == (350_000_000, 536_870_912)
        files["/sys/fs/cgroup/memory.max"] = "max\n"  # no container limit: the machine's memory
        assert pdfexport.memory_use() == (350_000_000, 8_000_000 * 1024)
        with env_vars(PDF_MEMORY_LIMIT_MB="512"):
            assert pdfexport.memory_use() == (350_000_000, 512 * MB)
    files = {
        "/sys/fs/cgroup/memory/memory.usage_in_bytes": "300000000\n",
        "/sys/fs/cgroup/memory/memory.limit_in_bytes": "268435456\n",
        "/sys/fs/cgroup/memory/memory.stat": "cache 1\ntotal_inactive_file 100000000\n",
    }
    with patched(pdfexport, _read=lambda path: files.get(path, "")), env_vars(PDF_MEMORY_LIMIT_MB=None):
        assert pdfexport.memory_use() == (200_000_000, 268_435_456)  # cgroup v1
    with patched(pdfexport, _read=lambda path: ""), env_vars(PDF_MEMORY_LIMIT_MB=None):
        assert pdfexport.memory_use() is None  # not Linux
    print("ok  test_memory_use_reads_the_container_limit")


def test_settings_reach_the_pdf_process_and_headless_shell_comes_first():
    env = pdf_env({"PDF_PART_ROWS": "150", "PDF_MEMORY_LIMIT_MB": "512", "GITHUB_TOKEN_X": "secret", "PATH": "/bin"})
    assert env["PDF_PART_ROWS"] == "150" and env["PDF_MEMORY_LIMIT_MB"] == "512" and "GITHUB_TOKEN_X" not in env
    found = {"chromium": "/usr/bin/chromium", "chromium-headless-shell": "/usr/bin/chromium-headless-shell"}
    with patched(pdfexport.shutil, which=found.get):
        candidates = pdfexport._browser_candidates()
    assert candidates.index("/usr/bin/chromium-headless-shell") < candidates.index("/usr/bin/chromium")
    print("ok  test_settings_reach_the_pdf_process_and_headless_shell_comes_first")


def test_real_browser_prints_every_commit_once():
    """End to end with the installed Edge/Chrome: the report's own script
    prints each part, and the joined PDF has every commit exactly once."""
    if pdfexport.find_browser() is None:
        print("skip test_real_browser_prints_every_commit_once (no Edge/Chrome)")
        return
    commits = _commits({"2026-01": 450, "2026-02": 20})
    with tempfile.TemporaryDirectory() as tmp:
        html = Path(tmp) / "report.html"
        html.write_text(_report_html({"2026-01": 450, "2026-02": 20}), encoding="utf-8")
        with env_vars(PDF_PART_ROWS="200"):
            pdf = pdfexport.export_pdf(html)
        assert pdf is not None, "the browser printed nothing"
        text = "\n".join(page.extract_text() or "" for page in PdfReader(pdf).pages)
    counts = collections.Counter(re.findall(r"\b[0-9a-f]{7}\b", text))
    shas = [sha[:7] for sha in commits["sha"]]
    assert all(counts[sha] == 1 for sha in shas), [sha for sha in shas if counts[sha] != 1][:10]
    # The parts after the first start mid-January, under a repeated header.
    assert text.upper().count("JANUARY 2026 (CONTINUED)") == 2, text[:2000]
    for once in ("At a glance", "Appendix — complete commit timeline", "Generated by github-contrib"):
        assert text.count(once) == 1, once
    print("ok  test_real_browser_prints_every_commit_once")


def _all_tests():
    return [v for k, v in sorted(globals().items()) if k.startswith("test_") and callable(v)]


def main() -> int:
    failures = 0
    for test in _all_tests():
        try:
            test()
        except Exception as exc:  # noqa: BLE001
            failures += 1
            print(f"FAIL {test.__name__}: {exc!r}")
            import traceback
            traceback.print_exc()
    total = len(_all_tests())
    print(f"\n{total - failures}/{total} tests passed.")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
